export const GET_FAVORITES='GET_FAVORITES';
export const ON_FAVORITE_ADD= 'ON_FAVORITE_ADD';
export const ON_FAVORITE_DELETE= 'ON_FAVORITE_DELETE';

export const SET_SELECTED = 'SET_SELECTED';
export const FORECAST_FETCH_SUCCESS ='FORECAST_FETCH_SUCCESS';
export const CURRENT_WEATHER_SUCCESS= 'CURRENT_WEATHER_SUCCESS';

export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const SET_LOADING = 'SET_LOADING';